### ISSUE TITLE
[BE] Elastic Search 적용하기

### ISSUE THREAD

**Issue by janeljs** [janeljs/issue-tracker#46]
- https://esbook.kimjmin.net/
- https://www.baeldung.com/spring-data-elasticsearch-tutorial
- https://github.com/spring-projects/spring-data-elasticsearch
- https://docs.spring.io/spring-data/elasticsearch/docs/4.2.1/reference/html/#reference
- https://velog.io/@jakeseo_me/%EC%97%98%EB%9D%BC%EC%8A%A4%ED%8B%B1%EC%84%9C%EC%B9%98-%EC%95%8C%EC%95%84%EB%B3%B4%EA%B8%B0-1-%EC%97%98%EB%9D%BC%EC%8A%A4%ED%8B%B1%EC%84%9C%EC%B9%98%EB%8A%94-%EA%B2%80%EC%83%89%EC%97%94%EC%A7%84%EC%9D%B4%EB%8B%A4
- https://www.youtube.com/watch?v=bYiNlCaaRiI

**Comment by eNoLJ** [comment]
https://velog.io/@hanblueblue/번역-spring-data-elasticsearch

**Comment by janeljs** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html

**Comment by janeljs** [comment]
https://www.elastic.co/kr/logstash

**Comment by janeljs** [comment]
[엘라스틱 서치와 로그스태시로 Mysql에서 필요한 데이터만 가져와서 검색/분석하고 대시보드 만들기](https://blog.naver.com/olpaemi/221076471642)


https://datascience-enthusiast.com/Miscellaneous/MySQL_to_ELK.html

**Comment by janeljs** [comment]
https://blog.naver.com/olpaemi/221074850627

**Comment by janeljs** [comment]
[How to synchronize MySQL Database with ElasticSearch And perform data querying in a Spring Boot Application](https://dev.to/yassinesabri/how-to-synchronize-mysql-database-with-elasticsearch-and-perform-data-querying-in-a-spring-boot-application-k8g)

**Comment by janeljs** [comment]
https://programmertoday.com/spring-boot-elastic-search-with-spring-data-jpa/

**Comment by janeljs** [comment]
JPA repository랑 elastic search repository 둘 다 쓰는 법
- https://stackoverflow.com/questions/32878813/how-do-you-use-both-spring-data-jpa-and-spring-data-elasticsearch-repositories-o

**Comment by janeljs** [comment]
https://github.com/TechPrimers/spring-data-elastic-example-1

**Comment by janeljs** [comment]
https://devfunny.tistory.com/365

**Comment by janeljs** [comment]
https://devfunny.tistory.com/419

**Comment by janeljs** [comment]
elasticsearch 설치
- https://velog.io/@qnfmtm666/elasticsearch-Elasticsearch-%EC%84%A4%EC%B9%98%ED%95%98%EA%B8%B0-Ubuntu-20.04

docker 기반 elasticsearch 설치
- https://jinhokwon.github.io/devops/elasticsearch/elasticsearch-docker/

**Comment by janeljs** [comment]
logstash를 이용하여 mysql과 elasticsearch 동기화
- https://www.elastic.co/kr/blog/how-to-keep-elasticsearch-synchronized-with-a-relational-database-using-logstash

**Comment by janeljs** [comment]
update by query
- https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html

**Comment by janeljs** [comment]
ngram
- https://findstar.pe.kr/2018/07/14/elasticsearch-wildcard-to-ngram/
- unigram이용하면 될듯
- https://stackoverflow.com/questions/45851917/n-gram-implementaion-in-spring-boot-elasticsearch
- http://www.donsdev.me/devlogs/141
