### ISSUE TITLE
[FE] 라벨 페이지

### ISSUE THREAD

**Issue by skawnkk** [janeljs/issue-tracker#84]
## 마크업
- [X] 옵션 및 리스트 부분 마크업
- [x] 라벨 추가 마크업 
- [x] 라벨 편집 마크업

## API 요청

- [x] 라벨 페이지 데이터 요청
- [x] 라벨 생성 요청
- [x] 라벨 삭제 요청

## 로직

- [x] 라벨 생성
- [x] 라벨 생성시 컬러 조절
- [x] 라벨 삭제

**Comment by hayoung123** [comment]
라벨 페이지 완료했습니다!
