### ISSUE TITLE
[FE] 이슈상세페이지 제목 수정 

### ISSUE THREAD

**Issue by skawnkk** [janeljs/issue-tracker#95]
- [X] 제목수정 마크업
- [X] 편집/뷰 모드에 따른 렌더링처리
- [x] 편집완료 시 API 요청
- [x] 수정한결과로 리렌더
- [x] 문제발견: 리스트 페이지에선 업데이트가 안됨.

**Comment by hayoung123** [comment]
제목이 다르게 나오는 오류 수정했습니다
